### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by visheshdembla** [airavata-courses/Swishh#36]
Hi guys,
I went through the repo and reviewed some parts of the code. In the short amount of time, I observed a few things. Could you have a look at these?

1. There is no separate branch for each microservice for CI/CD.
2. CORS seems to be disabled on your individual microservices, which is not a good practice. I think it needs to be enabled even for the microservices.
3. I don't think your files are being encrypted before being stored on the google drive. I think we need to handle this.

Can you have a look at these and let me know if these are valid concerns?

**Comment by hbondala** [comment]
Thanks @visheshdembla . Will review these issues for further releases
